services:
  - type: web
    name: makaut-backend
    env: node
    repo: https://github.com/paraiaritra/MAKAUT-Alumni-Portal
    branch: main
    root: backend
    buildCommand: 'npm install'
    startCommand: 'npm start'
    plan: free
